const MOCK_DETAIL_DATA: Record<string, Record<string, unknown>> = {
  "1001": {
    skillName: "폭풍검",
    times: 45,
    damageAmount: 1200000,
    critTimes: 30,
    parryTimes: 5,
    backTimes: 20,
    perfectTimes: 10,
    doubleTimes: 8,
    dotDamageAmount: 150000,
    dotTimes: 45,
  },
  "1002": {
    skillName: "대지의 응보 (1회 추가시전)",
    times: 38,
    damageAmount: 980000,
    critTimes: 22,
    parryTimes: 3,
    backTimes: 15,
    perfectTimes: 7,
    doubleTimes: 5,
    dotDamageAmount: 0,
    dotTimes: 0,
  },
  "1003": {
    skillName: "대지가르기",
    times: 20,
    damageAmount: 750000,
    critTimes: 12,
    parryTimes: 2,
    backTimes: 8,
    perfectTimes: 4,
    doubleTimes: 3,
    dotDamageAmount: 0,
    dotTimes: 0,
  },
  "1004": {
    skillName: "번개일격",
    times: 60,
    damageAmount: 520000,
    critTimes: 40,
    parryTimes: 1,
    backTimes: 25,
    perfectTimes: 15,
    doubleTimes: 12,
    dotDamageAmount: 80000,
    dotTimes: 60,
  },
  "1005": {
    skillName: "강철방어",
    times: 10,
    damageAmount: 200000,
    critTimes: 3,
    parryTimes: 8,
    backTimes: 1,
    perfectTimes: 2,
    doubleTimes: 1,
    dotDamageAmount: 0,
    dotTimes: 0,
  },
  "1006": {
    skillName: "대지의 응보 (1회 추가시전)",
    times: 38,
    damageAmount: 980000,
    critTimes: 22,
    parryTimes: 3,
    backTimes: 15,
    perfectTimes: 7,
    doubleTimes: 5,
    dotDamageAmount: 0,
    dotTimes: 0,
  },
  "1007": {
    skillName: "대지가르기",
    times: 20,
    damageAmount: 750000,
    critTimes: 12,
    parryTimes: 2,
    backTimes: 8,
    perfectTimes: 4,
    doubleTimes: 3,
    dotDamageAmount: 0,
    dotTimes: 0,
  },
  "1008": {
    skillName: "번개일격",
    times: 60,
    damageAmount: 520000,
    critTimes: 40,
    parryTimes: 1,
    backTimes: 25,
    perfectTimes: 15,
    doubleTimes: 12,
    dotDamageAmount: 80000,
    dotTimes: 60,
  },
  "1009": {
    skillName: "강철방어",
    times: 10,
    damageAmount: 200000,
    critTimes: 3,
    parryTimes: 8,
    backTimes: 1,
    perfectTimes: 2,
    doubleTimes: 1,
    dotDamageAmount: 0,
    dotTimes: 0,
  },
  "10010": {
    skillName: "대지의 응보 (1회 추가시전)",
    times: 38,
    damageAmount: 980000,
    critTimes: 22,
    parryTimes: 3,
    backTimes: 15,
    perfectTimes: 7,
    doubleTimes: 5,
    dotDamageAmount: 0,
    dotTimes: 0,
  },
  "10011": {
    skillName: "대지가르기",
    times: 20,
    damageAmount: 750000,
    critTimes: 12,
    parryTimes: 2,
    backTimes: 8,
    perfectTimes: 4,
    doubleTimes: 3,
    dotDamageAmount: 0,
    dotTimes: 0,
  },
  "10012": {
    skillName: "번개일격",
    times: 60,
    damageAmount: 520000,
    critTimes: 40,
    parryTimes: 1,
    backTimes: 25,
    perfectTimes: 15,
    doubleTimes: 12,
    dotDamageAmount: 80000,
    dotTimes: 60,
  },
  "10013": {
    skillName: "강철방어",
    times: 10,
    damageAmount: 200000,
    critTimes: 3,
    parryTimes: 8,
    backTimes: 1,
    perfectTimes: 2,
    doubleTimes: 1,
    dotDamageAmount: 0,
    dotTimes: 0,
  },
};
const MOCK_DATA = {
  map: {
    "1": {
      user: { id: 1, nickname: "나", job: "검성", isExecutor: true },
      dps: 45000,
      damageContribution: 35.5,
    },
    "2": {
      user: { id: 2, nickname: "딜러A딜러A딜러A딜러A딜러A딜러A", job: "마도성", isExecutor: false },
      dps: 45000,
      damageContribution: 35.5,
    },
    "3": {
      user: { id: 3, nickname: "딜러B", job: "정령성", isExecutor: false },
      dps: 30000,
      damageContribution: 20.1,
    },
    "4": {
      user: { id: 4, nickname: "딜러C", job: "호법성", isExecutor: false },
      dps: 15000,
      damageContribution: 4.2,
    },
    "5": {
      user: { id: 5, nickname: "서폿A", job: "치유성", isExecutor: false },
      dps: 3000,
      damageContribution: 2.1,
    },
    "6": {
      user: { id: 6, nickname: "서폿B", job: "수호성", isExecutor: false },
      dps: 1500,
      damageContribution: 1.5,
    },
  },
  targetName: "증합체 바고트",
  battleTime: 93000,
};

export const injectMockDpsData = () => {
  if ((window as any).javaBridge) return;

  (window as any).javaBridge = {
    getDpsData: () => JSON.stringify(MOCK_DATA),
    getBattleDetail: (_id: string) => JSON.stringify(MOCK_DETAIL_DATA),
  };
};
